#name: cd
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  cd:
#    runs-on: ubuntu-latest
#
#    env:
#      BRANCH: gh-pages
#
#    steps:
#      - name: Checkout ğŸ›
#        uses: actions/checkout@master
#
#      - name: Build thesis âš™ï¸
#        uses: xu-cheng/latex-action@v2
#        with:
#          root_file: thesis.tex
#          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode --output-directory=./dist -f
#
#      - name: Deploy application ğŸš€
#        uses: JamesIves/github-pages-deploy-action@releases/v3
#        with:
#          GITHUB_TOKEN: ${{ github.TOKEN }}
#          BRANCH: ${{ env.BRANCH }}
#          FOLDER: dist
